_core:
  default_config_hash: cceqUa945af6yMPEeM1pWJQoA-tumoAqhThW2xGoZ04
check:
  disabled_extensions: false
  interval_days: 1
fetch:
  url: 'https://updates.drupal.org/release-history'
  max_attempts: 2
  timeout: 30
notification:
  emails:
    - admin@adaptivetechnologies.com
  threshold: all
